name: Auto Format(Black)

on:
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install formatter
      run: pip install black

    - name: Run formatter
      run: black . --exclude 'eigen-3\.4\.0'

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-format with black" || echo "No changes"
        git push
